const text = {
    investing_through: "Investing through?",
    proceed_with_a_new_folio_button: "Proceed with a New Folio",
    direct_button: "Direct",
    advisor_button: "Advisor / RIA",
    distributor_button: "Distributor(ARN)",
    folio_heading: "Future Ready SIP",
    folio_subheading: "Be Future Ready by starting a SIP today and planning your SWP for future",
    SIP_scheme_Input_helper: "Start by setting up a SIP in a scheme of your choice. Remember you cannot choose ELSS or Target Maturity Funds for Future Ready SIP",
    SIP_amount_label: "SIP Amount",
    SIP_amount_input_helper:"Select the scheme and amount",
    SIP_start_date_input_helper:"Choose the start date and duration. Frequency will be monthly.\n" +
        "                        The selected duration will determine the date of the last SIP.",
    next: "Next",
    SIP_top_up_input_helper: "Next, decide if you want to Top-up your SIP. If yes, mention your top-up amount, frequency and the maximum top-up amount",
    SIP_top_up_input_label: "Do you want to Top-up this SIP?",
    SIP_first_payment_input_helper: "Lastly decide if you wish to start your SIP right away.",
    SIP_first_payment_input_label:"Do you want to make 1st SIP payment now?",
    SWP_switch_notice: "Your entire investment amount (all units) will be switched to this scheme 15 days after your last SIP installment date.",
    button_promotion: "Be Future Ready by starting a SIP today and planning your SWP for future",
    switch_date_label: "Switch Date",
    SWP_scheme_input_helper: "Now choose if your SWP should be from the same scheme as your SIP or from another scheme. If you choose another scheme, a one time switch of your entire investment amount (all units) will occur in 15 days of your last SIP date.",
    SWP_frequency_label: "Frequency",
    SWP_amount_input_helper: "Select the SWP amount - Choose from the recommended amount or enter your own amount",
    SWP_amount_label: "SWP Amount",
    SWP_start_date_notice:"Your SWP start date will be calculated based on the interval chosen",
    SWP_start_date_label: "SWP Start Date",
    SWP_start_date_helper: "Next, select the interval to start the SWP after and it's frequency."
}
export default text